server:
  port: 8768

spring:
  application:
    name: ads-service

  main:
    lazy-initialization: false
    banner-mode: off
#  jmx:
#    enabled: false
#  autoconfigure:
#    exclude:
#      - org.springframework.boot.autoconfigure.admin.SpringApplicationAdminJmxAutoConfiguration
#      - org.springframework.boot.autoconfigure.jmx.JmxAutoConfiguration

  datasource:
    url: ${DB_URL_ADS}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 3
      minimum-idle: 1
      connection-timeout: 30000
      idle-timeout: 300000
      max-lifetime: 600000
      leak-detection-threshold: 30000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      ssl:
        enabled: true

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    virtual-host: ${RABBITMQ_VHOST:/}
    cache:
      connection:
        mode: channel
      channel:
        size: 5

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics
  endpoint:
    health:
      show-details: never
  metrics:
    tags:
      application: ${spring.application.name}

eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20

minio:
  url: ${MINIO_ENDPOINT}
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET}
  bucket:
    ads: ${MINIO_ADS_BUCKET:ads-audio}

open:
  api:
    title: Ads Service API
    version: 1.0.0
    server-url: ${GATEWAY_URL:http://localhost:8080}/service-ads
    server-description: API Gateway

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    iuh.fit.se.adsservice: INFO

internal:
  service-secret: ${INTERNAL_SERVICE_SECRET}
gateway:
  internal-secret: ${GATEWAY_INTERNAL_SECRET:}
