server:
  port: 8767

spring:
  application:
    name: social-service

  data:
    mongodb:
      uri: ${MONGODB_URI}
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

jwt:
  signerKey: ${JWT_SECRET}

app:
  frontend:
    url: ${FRONTEND_URL:http://localhost:3000}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    iuh.fit.se.socialservice: DEBUG


minio:
  url: ${MINIO_ENDPOINT}
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET}
  bucket:
    ai-training-data: ${MINIO_AI_BUCKET:ai-training-data}

open:
  api:
    server-url: ${GATEWAY_URL:http://localhost:8080}/service-social
    server-description: API Gateway

