services:
  recommendation-ml:
    profiles: ["advance"]

  recommendation-service:
    environment:
      RECOMMENDATION_MODE: basic
    depends_on:
      discovery-server:
        condition: service_healthy
