server:
  port: 8080

spring:
  application:
    name: api-gateway
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      filter:
        request-rate-limiter:
          deny-empty-key: false
          empty-key-status-code: 200

      routes:

        # ================= IDENTITY =================

        - id: identity-service-auth
          uri: lb://IDENTITY-SERVICE
          predicates:
            - Path=/auth/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@ipAndUserKeyResolver}"
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
                redis-rate-limiter.requestedTokens: 1

        - id: identity-service-users
          uri: lb://IDENTITY-SERVICE
          predicates:
            - Path=/users/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@ipAndUserKeyResolver}"
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                redis-rate-limiter.requestedTokens: 1

        - id: identity-swagger
          uri: lb://IDENTITY-SERVICE
          predicates:
            - Path=/service-identity/**
          filters:
            - StripPrefix=1
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@ipAndUserKeyResolver}"
                redis-rate-limiter.replenishRate: 20
                redis-rate-limiter.burstCapacity: 40
                redis-rate-limiter.requestedTokens: 1

        # ================= MUSIC =================

        - id: music-service-api
          uri: lb://MUSIC-SERVICE
          predicates:
            - Path=/songs/**, /albums/**, /genres/**, /artists/**, /playlists/**, /admin/songs/**, /admin/jamendo/**, /admin/reports/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@ipAndUserKeyResolver}"
                redis-rate-limiter.replenishRate: 30
                redis-rate-limiter.burstCapacity: 60
                redis-rate-limiter.requestedTokens: 1

        - id: music-swagger
          uri: lb://MUSIC-SERVICE
          predicates:
            - Path=/service-music/**
          filters:
            - StripPrefix=1
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@ipAndUserKeyResolver}"
                redis-rate-limiter.replenishRate: 20
                redis-rate-limiter.burstCapacity: 40
                redis-rate-limiter.requestedTokens: 1

        # ================= PAYMENT =================

        - id: payment-service-payments
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payments/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@ipAndUserKeyResolver}"
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                redis-rate-limiter.requestedTokens: 1

        - id: ads-service-api
          uri: lb://ADS-SERVICE
          predicates:
            - Path=/ads/**, /admin/ads/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@ipAndUserKeyResolver}"
                redis-rate-limiter.replenishRate: 20
                redis-rate-limiter.burstCapacity: 40
                redis-rate-limiter.requestedTokens: 1

        - id: payment-service-subscriptions
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/subscriptions/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@ipAndUserKeyResolver}"
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                redis-rate-limiter.requestedTokens: 1

        - id: payment-service-admin
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/admin/subscriptions/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@ipAndUserKeyResolver}"
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
                redis-rate-limiter.requestedTokens: 1

        - id: payment-swagger
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/service-payment/**
          filters:
            - StripPrefix=1
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@ipAndUserKeyResolver}"
                redis-rate-limiter.replenishRate: 20
                redis-rate-limiter.burstCapacity: 40
                redis-rate-limiter.requestedTokens: 1

        # ================= SOCIAL =================

        - id: social-service-api
          uri: lb://SOCIAL-SERVICE
          predicates:
            - Path=/social/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@ipAndUserKeyResolver}"
                redis-rate-limiter.replenishRate: 20
                redis-rate-limiter.burstCapacity: 40
                redis-rate-limiter.requestedTokens: 1

        - id: social-swagger
          uri: lb://SOCIAL-SERVICE
          predicates:
            - Path=/service-social/**
          filters:
            - StripPrefix=1
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@ipAndUserKeyResolver}"
                redis-rate-limiter.replenishRate: 20
                redis-rate-limiter.burstCapacity: 40
                redis-rate-limiter.requestedTokens: 1

        # ================= RECOMMENDATION =================

        - id: recommendation-service-api
          uri: lb://RECOMMENDATION-SERVICE
          predicates:
            - Path=/recommendations/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@ipAndUserKeyResolver}"
                redis-rate-limiter.replenishRate: 15
                redis-rate-limiter.burstCapacity: 30
                redis-rate-limiter.requestedTokens: 1

        - id: recommendation-swagger
          uri: lb://RECOMMENDATION-SERVICE
          predicates:
            - Path=/service-recommendation/**
          filters:
            - StripPrefix=1
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@ipAndUserKeyResolver}"
                redis-rate-limiter.replenishRate: 20
                redis-rate-limiter.burstCapacity: 40
                redis-rate-limiter.requestedTokens: 1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  signerKey: ${JWT_SECRET:}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: identity-service
        url: /service-identity/v3/api-docs
      - name: music-service
        url: /service-music/v3/api-docs
      - name: payment-service
        url: /service-payment/v3/api-docs
      - name: social-service
        url: /service-social/v3/api-docs
      - name: recommendation-service
        url: /service-recommendation/v3/api-docs
  api-docs:
    enabled: true