server:
  port: 8761
spring:
  application:
    name: discovery-server

  main:
    lazy-initialization: false
    banner-mode: off
#  jmx:
#    enabled: false
#  autoconfigure:
#    exclude:
#      - org.springframework.boot.autoconfigure.admin.SpringApplicationAdminJmxAutoConfiguration
#      - org.springframework.boot.autoconfigure.jmx.JmxAutoConfiguration

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics
  endpoint:
    health:
      show-details: never
  metrics:
    tags:
      application: ${spring.application.name}
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false