apiVersion: 1

datasources:
  # Prometheus datasource
  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      timeInterval: "15s"
    editable: false

  # Zipkin datasource cho distributed tracing
  - name: Zipkin
    type: zipkin
    uid: zipkin
    access: proxy
    url: http://zipkin:9411
    editable: false