server:
  port: 8764
  compression:
    enabled: true
    mime-types:
      - application/json
      - application/javascript
      - text/plain
    min-response-size: 1024

spring:
  application:
    name: music-service

  main:
    lazy-initialization: false
    banner-mode: off
  jmx:
    enabled: false
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.admin.SpringApplicationAdminJmxAutoConfiguration
      - org.springframework.boot.autoconfigure.jmx.JmxAutoConfiguration

  datasource:
    url: ${DB_URL_MUSIC}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 3
      minimum-idle: 1
      connection-timeout: 30000
      idle-timeout: 300000
      max-lifetime: 600000
      leak-detection-threshold: 30000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 210MB

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}
      ssl:
        enabled: true

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    virtual-host: ${RABBITMQ_VHOST:/}
    cache:
      connection:
        mode: channel
      channel:
        size: 5

  cache:
    type: redis
    redis:
      time-to-live: 600000

eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20

minio:
  url: ${MINIO_ENDPOINT}
  public-url: ${MINIO_PUBLIC_URL}
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET}
  bucket:
    raw-songs: ${MINIO_RAW_BUCKET:music}
    public-songs: ${MINIO_PUBLIC_BUCKET:public-songs}

spotify:
  client-id: ${SPOTIFY_CLIENT_ID:}
  client-secret: ${SPOTIFY_CLIENT_SECRET:}

# ── Jamendo API ────────────────────────────────────────────────────────────────
jamendo:
  client-id: ${JAMENDO_CLIENT_ID}

open:
  api:
    title: Music Service API
    version: 1.0.0
    server-url: ${GATEWAY_URL:http://localhost:8080}/service-music
    server-description: API Gateway

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics
  endpoint:
    health:
      show-details: never
  metrics:
    tags:
      application: ${spring.application.name}

internal:
  service-secret: ${INTERNAL_SERVICE_SECRET}
gateway:
  internal-secret: ${GATEWAY_INTERNAL_SECRET:}